/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.Font;
import javax.swing.BoxLayout;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.SwingConstants;
import javax.swing.border.Border;
import javax.swing.border.EmptyBorder;

/**
 *
 * @author iqbalrahmatullah
 */
public class DetailTransaction extends javax.swing.JFrame {

    /**
     * Creates new form DetailTransaction
     */
    public DetailTransaction() {
        initComponents();
//        JPanel panelSeat = new JPanel();
//        panelSeat.setPreferredSize(new Dimension(430, 100));
//        panelSeat.setLayout(null);
//        panelSeat.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(41, 128, 185), 1, true));
//        JLabel imageTrx = new JLabel(new ImageIcon(getClass().getResource("/images/train.png")));
//        imageTrx.setLocation(215, 1);
//        imageTrx.setSize(50, 40);
//        imageTrx.setHorizontalAlignment(0);
//        
//        JLabel label = new JLabel("Nama : cek");
//        label.setFont(new Font("PT Sans Narrow", Font.BOLD, 13));
//        label.setLocation(3, 23);
//        label.setSize(70, 40);
//        label.setHorizontalAlignment(0);
//
//        panelSeat.add(imageTrx);
//        panelSeat.add(label);
//        mainPanel.add(panelSeat);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rightPanel4 = new javax.swing.JPanel();
        Applogo4 = new javax.swing.JLabel();
        Train8 = new javax.swing.JLabel();
        Train9 = new javax.swing.JLabel();
        buttonHome4 = new javax.swing.JButton();
        mainPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        rightPanel4.setBackground(new java.awt.Color(41, 128, 185));

        Applogo4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/applogo.png"))); // NOI18N

        Train8.setFont(new java.awt.Font("PT Sans Narrow", 1, 36)); // NOI18N
        Train8.setForeground(new java.awt.Color(255, 255, 255));
        Train8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Train8.setText("TRANSACTION");

        Train9.setFont(new java.awt.Font("PT Sans Narrow", 1, 36)); // NOI18N
        Train9.setForeground(new java.awt.Color(255, 255, 255));
        Train9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Train9.setText("DETAIL");

        buttonHome4.setBackground(new java.awt.Color(255, 153, 0));
        buttonHome4.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        buttonHome4.setForeground(new java.awt.Color(255, 255, 255));
        buttonHome4.setText("Back To Home");
        buttonHome4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonHome4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout rightPanel4Layout = new javax.swing.GroupLayout(rightPanel4);
        rightPanel4.setLayout(rightPanel4Layout);
        rightPanel4Layout.setHorizontalGroup(
            rightPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rightPanel4Layout.createSequentialGroup()
                .addGroup(rightPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(rightPanel4Layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addGroup(rightPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Train8, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rightPanel4Layout.createSequentialGroup()
                                .addGroup(rightPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Applogo4)
                                    .addComponent(Train9))
                                .addGap(51, 51, 51))))
                    .addGroup(rightPanel4Layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(buttonHome4, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(92, Short.MAX_VALUE))
        );
        rightPanel4Layout.setVerticalGroup(
            rightPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rightPanel4Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(Applogo4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Train9)
                .addGap(2, 2, 2)
                .addComponent(Train8)
                .addGap(18, 18, 18)
                .addComponent(buttonHome4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(106, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(rightPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rightPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonHome4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonHome4ActionPerformed
        Home homeFrame = new Home();
        homeFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_buttonHome4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DetailTransaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DetailTransaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DetailTransaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DetailTransaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DetailTransaction().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Applogo;
    private javax.swing.JLabel Applogo1;
    private javax.swing.JLabel Applogo2;
    private javax.swing.JLabel Applogo3;
    private javax.swing.JLabel Applogo4;
    private javax.swing.JLabel Train;
    private javax.swing.JLabel Train1;
    private javax.swing.JLabel Train2;
    private javax.swing.JLabel Train3;
    private javax.swing.JLabel Train4;
    private javax.swing.JLabel Train5;
    private javax.swing.JLabel Train6;
    private javax.swing.JLabel Train7;
    private javax.swing.JLabel Train8;
    private javax.swing.JLabel Train9;
    private javax.swing.JButton buttonHome;
    private javax.swing.JButton buttonHome1;
    private javax.swing.JButton buttonHome2;
    private javax.swing.JButton buttonHome3;
    private javax.swing.JButton buttonHome4;
    public static javax.swing.JPanel mainPanel;
    private javax.swing.JPanel rightPanel;
    private javax.swing.JPanel rightPanel1;
    private javax.swing.JPanel rightPanel2;
    private javax.swing.JPanel rightPanel3;
    private javax.swing.JPanel rightPanel4;
    // End of variables declaration//GEN-END:variables
}
